Check result code of decryption

diff --git a/bin/pw b/bin/pw
--- a/bin/pw
+++ b/bin/pw
@@ -49,6 +49,8 @@ ERR_MISSING=10      # PWFILE is missing
 ERR_ENC=11          # Error encrypting with gpg
 ERR_COMMIT=12       # Error committing to git
 ERR_PUSHD=13        # Error finding base directory
+ERR_DECRYPT=14      # Error whilst encrypting passwords.txt => passwords.txt.gpg
+ERR_UNKOWN=100      # Don't know what went wrong, check output
 
 editor=`which $VISUAL`
 if [ "$editor"x == "x" ]; then
@@ -73,6 +75,14 @@ fi
 decrypt () {
 	if [ ! -f $PWFILE ]; then
 		gpg $GPG_DEC_OPTS $PWENC
+		result=$?
+		if [ "$result" == "2" ]; then
+			echo "Could not decrypt, bad passphrase?"
+			quit $ERR_DECRYPT
+		elif [ "$result" != "0" ]; then
+			echo "Unknown response after decrypt ($result)"
+			quit $ERR_UNKONWN
+		fi
 	fi
 }
 
